apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-1
  labels:
    name: mysql
spec:
  replicas: 3
  template: 
    metadata:
      labels:
        component: mysql
    spec:
      imagePullSecrets:
      - name: mysql
      containers:
      - name: mysql
        image: mysql:boshao
        volumeMounts:
        - mountPath: /data
          name: storage
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: mysql
      volumes:
      - name: storage
        emptyDir: {}

